local exe4_mojifont = bnlc_mod_loader.read_mod_contents("exe4\\eng_mojiFont.fnt")
local exe4_font8x16 = bnlc_mod_loader.read_mod_contents("exe4\\font8x16_eng_00.pak")
local exe4_subfont = bnlc_mod_loader.read_mod_contents("exe4\\subfont_eng_00.pak")
bnlc_mod_loader.write_exe_dat_contents("exe4.dat", "exe4/data/font/eng_mojiFont.fnt", exe4_mojifont)
bnlc_mod_loader.write_exe_dat_contents("exe4b.dat", "exe4b/data/font/eng_mojiFont.fnt", exe4_mojifont)
bnlc_mod_loader.write_exe_dat_contents("exe4.dat", "exe4/data/ui/font8x16_eng_00.pak", exe4_font8x16)
bnlc_mod_loader.write_exe_dat_contents("exe4b.dat", "exe4b/data/ui/font8x16_eng_00.pak", exe4_font8x16)
bnlc_mod_loader.write_exe_dat_contents("exe4.dat", "exe4/data/ui/subfont_eng_00.pak", exe4_subfont)
bnlc_mod_loader.write_exe_dat_contents("exe4b.dat", "exe4b/data/ui/subfont_eng_00.pak", exe4_subfont)

local exe5_mojifont = bnlc_mod_loader.read_mod_contents("exe5\\eng_mojiFont.fnt")
local exe5_font8x16 = bnlc_mod_loader.read_mod_contents("exe5\\font8x16_eng_00.pak")
local exe5_subfont = bnlc_mod_loader.read_mod_contents("exe5\\subfont_eng_00.pak")
bnlc_mod_loader.write_exe_dat_contents("exe5.dat", "exe5/data/font/eng_mojiFont.fnt", exe5_mojifont)
bnlc_mod_loader.write_exe_dat_contents("exe5k.dat", "exe5k/data/font/eng_mojiFont.fnt", exe5_mojifont)
bnlc_mod_loader.write_exe_dat_contents("exe5.dat", "exe5/data/ui/font8x16_eng_00.pak", exe5_font8x16)
bnlc_mod_loader.write_exe_dat_contents("exe5k.dat", "exe5k/data/ui/font8x16_eng_00.pak", exe5_font8x16)
bnlc_mod_loader.write_exe_dat_contents("exe5.dat", "exe5/data/ui/subfont_eng_00.pak", exe5_subfont)
bnlc_mod_loader.write_exe_dat_contents("exe5k.dat", "exe5k/data/ui/subfont_eng_00.pak", exe5_subfont)

local exe6_mojifont = bnlc_mod_loader.read_mod_contents("exe6\\eng_mojiFont.fnt")
local exe6_font8x16 = bnlc_mod_loader.read_mod_contents("exe6\\font8x16_eng_00.pak")
local exe6_subfont = bnlc_mod_loader.read_mod_contents("exe6\\subfont_eng_00.pak")
bnlc_mod_loader.write_exe_dat_contents("exe6.dat", "exe6/data/font/eng_mojiFont.fnt", exe6_mojifont)
bnlc_mod_loader.write_exe_dat_contents("exe6f.dat", "exe6f/data/font/eng_mojiFont.fnt", exe6_mojifont)
bnlc_mod_loader.write_exe_dat_contents("exe6.dat", "exe6/data/ui/font8x16_eng_00.pak", exe6_font8x16)
bnlc_mod_loader.write_exe_dat_contents("exe6f.dat", "exe6f/data/ui/font8x16_eng_00.pak", exe6_font8x16)
bnlc_mod_loader.write_exe_dat_contents("exe6.dat", "exe6/data/ui/subfont_eng_00.pak", exe6_subfont)
bnlc_mod_loader.write_exe_dat_contents("exe6f.dat", "exe6f/data/ui/subfont_eng_00.pak", exe6_subfont)
