local exe4_dat = chaudloader.exedat.open("exe4.dat")
local exe4b_dat = chaudloader.exedat.open("exe4b.dat")
local exe5_dat = chaudloader.exedat.open("exe5.dat")
local exe5k_dat = chaudloader.exedat.open("exe5k.dat")
local exe6_dat = chaudloader.exedat.open("exe6.dat")
local exe6f_dat = chaudloader.exedat.open("exe6f.dat")

local exe4_mojifont = chaudloader.modfiles.read_file("exe4\\eng_mojiFont.fnt")
local exe4_font8x16 = chaudloader.modfiles.read_file("exe4\\font8x16_eng_00.pak")
local exe4_subfont = chaudloader.modfiles.read_file("exe4\\subfont_eng_00.pak")
exe4_dat:write_file("exe4/data/font/eng_mojiFont.fnt", exe4_mojifont)
exe4b_dat:write_file("exe4b/data/font/eng_mojiFont.fnt", exe4_mojifont)
exe4_dat:write_file("exe4/data/ui/font8x16_eng_00.pak", exe4_font8x16)
exe4b_dat:write_file("exe4b/data/ui/font8x16_eng_00.pak", exe4_font8x16)
exe4_dat:write_file("exe4/data/ui/subfont_eng_00.pak", exe4_subfont)
exe4b_dat:write_file("exe4b/data/ui/subfont_eng_00.pak", exe4_subfont)

local exe5_mojifont = chaudloader.modfiles.read_file("exe5\\eng_mojiFont.fnt")
local exe5_font8x16 = chaudloader.modfiles.read_file("exe5\\font8x16_eng_00.pak")
local exe5_subfont = chaudloader.modfiles.read_file("exe5\\subfont_eng_00.pak")
exe5_dat:write_file("exe5/data/font/eng_mojiFont.fnt", exe5_mojifont)
exe5k_dat:write_file("exe5k/data/font/eng_mojiFont.fnt", exe5_mojifont)
exe5_dat:write_file("exe5/data/ui/font8x16_eng_00.pak", exe5_font8x16)
exe5k_dat:write_file("exe5k/data/ui/font8x16_eng_00.pak", exe5_font8x16)
exe5_dat:write_file("exe5/data/ui/subfont_eng_00.pak", exe5_subfont)
exe5k_dat:write_file("exe5k/data/ui/subfont_eng_00.pak", exe5_subfont)

local exe6_mojifont = chaudloader.modfiles.read_file("exe6\\eng_mojiFont.fnt")
local exe6_font8x16 = chaudloader.modfiles.read_file("exe6\\font8x16_eng_00.pak")
local exe6_subfont = chaudloader.modfiles.read_file("exe6\\subfont_eng_00.pak")
exe6_dat:write_file("exe6/data/font/eng_mojiFont.fnt", exe6_mojifont)
exe6f_dat:write_file("exe6f/data/font/eng_mojiFont.fnt", exe6_mojifont)
exe6_dat:write_file("exe6/data/ui/font8x16_eng_00.pak", exe6_font8x16)
exe6f_dat:write_file("exe6f/data/ui/font8x16_eng_00.pak", exe6_font8x16)
exe6_dat:write_file("exe6/data/ui/subfont_eng_00.pak", exe6_subfont)
exe6f_dat:write_file("exe6f/data/ui/subfont_eng_00.pak", exe6_subfont)
